[package]
name = "tribute"
version = "0.1.0"
authors = ["John Barker <dev@j16r.net>"]
edition = "2018"

[dependencies]
chrono = "0.4"
clap = "2.33"
coinbase-pro-rs = "0.3.4"
csv = "1.1.0"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5.1"
uuid = "0.7.4"
